export const blogData = [
  {
    id: 1,
    title: 'How to make a Wordpress Website - Step-By-Step for Beginners',
    image: '/images/Representation of user experience and interface design.png',
    date: 'December 25, 2023',
    desc: 'Web Design',
  },
  {
    id: 2,
    title: 'Top news about Nigeria economics, Updates News',
    image: '/images/Newspaper background concept.png',
    date: 'December 22, 2023',
    desc: 'Daily News',
  },
  {
    id: 3,
    title: 'Playing the best Game,  Call of Duties.',
    image: '/images/Gamification 3d rendering concept.png',
    date: 'December 19, 2023',
    heading: 'lorem ipsum ict',
    desc: 'Play store',
  },
  {
    id: 4,
    title: 'Daily Exercise, Are you Ready to ride on? ',
    image: '/images/Athlete ready to run with are you ready message.png',
    date: 'December 25, 2023',
    heading: 'lorem ipsum ict',
    desc: 'Play store',
  },
  {
    id: 5,
    title: 'How to make a Wordpress Website - Step-By-Step for Beginners',
    image: '/images/Representation of user experience and interface design.png',
    date: 'December 25, 2023',
    heading: 'lorem ipsum ict',
    desc: 'Web Design',
  },
  {
    id: 6,
    title: 'Playing the best Game,  Call of Duties.',
    image: '/images/Gamification 3d rendering concept.png',
    date: 'December 19, 2023',
    heading: 'lorem ipsum ict',
    desc: 'Play store',
  },
  {
    id: 7,
    title: 'Playing the best Game,  Call of Duties.',
    image: '/images/Gamification 3d rendering concept.png',
    date: 'December 19, 2023',
    heading: 'lorem ipsum ict',
    desc: 'Play store',
  },
  {
    id: 8,
    title: 'How to make a Wordpress Website - Step-By-Step for Beginners',
    image: '/images/Representation of user experience and interface design.png',
    date: 'December 25, 2023',
    desc: 'Web Design',
  },
  {
    id: 9,
    title: 'Daily Exercise, Are you Ready to ride on? ',
    image: '/images/Athlete ready to run with are you ready message.png',
    date: 'December 25, 2023',
    desc: 'Play store',
  },
  {
    id: 10,
    title: 'Top news about Nigeria economics, Updates News',
    image: '/images/Newspaper background concept.png',
    date: 'December 22, 2023',
    heading: 'lorem ipsum ict',
    desc: 'Play store',
  },
  {
    id: 11,
    title: 'Playing the best Game,  Call of Duties.',
    image: '/images/Gamification 3d rendering concept.png',
    date: 'December 19, 2023',
    desc: 'Play store',
  },
  {
    id: 12,
    title: 'How to make a Wordpress Website - Step-By-Step for Beginners',
    image: '/images/Representation of user experience and interface design.png',
    date: 'December 25, 2023',
    heading: 'lorem ipsum ict',
    desc: 'Web Design',
  },
]

export const blogData1 = [
  {
    id: 1,
    title: 'How to make a Wordpress Website - Step-By-Step for Beginners',
    image: '/images/Representation of user experience and interface design.png',
    date: 'December 25, 2023',
    heading: 'lorem ipsum ict',
    desc: 'Tutorial',
  },
  {
    id: 2,
    title: 'Playing the best Game,  Call of Duties.',
    image: '/images/Gamification 3d rendering concept.png',
    date: 'December 19, 2023',
    desc: 'Tutorial',
  },
  {
    id: 3,
    title: 'Daily Exercise, Are you Ready to ride on? ',
    image: '/images/Athlete ready to run with are you ready message.png',
    date: 'December 25, 2023',
    desc: 'Tutorial',
  },
  {
    id: 4,
    title: 'How to make a Wordpress Website - Step-By-Step for Beginners',
    image: '/images/Representation of user experience and interface design.png',
    date: 'December 25, 2023',
    heading: 'lorem ipsum ict',
    desc: 'Tutorial',
  },
  {
    id: 5,
    title: 'Playing the best Game,  Call of Duties.',
    image: '/images/Gamification 3d rendering concept.png',
    date: 'December 19, 2023',
    desc: 'Tutorial',
  },
  {
    id: 6,
    title: 'Daily Exercise, Are you Ready to ride on? ',
    image: '/images/Athlete ready to run with are you ready message.png',
    date: 'December 25, 2023',
    desc: 'Tutorial',
  },
  {
    id: 7,
    title: 'Playing the best Game,  Call of Duties.',
    image: '/images/Gamification 3d rendering concept.png',
    date: 'December 19, 2023',
    desc: 'Tutorial',
  },
  {
    id: 8,
    title: 'How to make a Wordpress Website - Step-By-Step for Beginners',
    image: '/images/Representation of user experience and interface design.png',
    date: 'December 25, 2023',
    heading: 'lorem ipsum ict',
    desc: 'Tutorial',
  },
  {
    id: 9,
    title: 'Playing the best Game,  Call of Duties.',
    image: '/images/Gamification 3d rendering concept.png',
    date: 'December 19, 2023',
    desc: 'Tutorial',
  },
]
